default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: anshabmk

development:
  <<: *default
  database: booking-manager-development

test:
  <<: *default
  database: booking-manager-test
  reconnect: true
